# Generated by Django 4.0.4 on 2022-05-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoGreen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='location',
        ),
        migrations.AddField(
            model_name='image',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
