# Generated by Django 4.0.4 on 2022-06-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoGreen', '0002_rename_description_image_location_image_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('date', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
