# Generated by Django 4.0.4 on 2022-06-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoGreen', '0003_userupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='cluster',
            field=models.FloatField(default=2, max_length=4),
        ),
    ]
