# Generated by Django 4.0.4 on 2022-06-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoGreen', '0004_userupload_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='cluster',
            field=models.IntegerField(default=2, max_length=4),
        ),
    ]
