# Generated by Django 4.0.4 on 2022-06-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoGreen', '0005_alter_userupload_area_alter_userupload_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='cluster',
            field=models.IntegerField(default=2),
        ),
    ]
